"""Generate the paper's three figures from numbers.tex, and nothing else.

Every plotted value is read from a macro in ../numbers.tex, the file audit_numbers.py checks against
the evidence at the milestone tag, so a figure cannot show a number the audit has not seen. The
figures are pgfplots code (vector, drawn by LaTeX; no plotting library is needed), written next to
this script and included by the sections.

Usage (from the repository root):
    python3 docs/research/paper/figures/make_figures.py          # write the three .tex files
    python3 docs/research/paper/figures/make_figures.py --check  # fail if they differ
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
NUMBERS = HERE.parent / "numbers.tex"


def macros() -> dict[str, str]:
    """Macro name -> printed value, for the number macros of numbers.tex."""
    text = NUMBERS.read_text()
    found = re.findall(
        r"\\newcommand\{\\(n[A-Z]\w*)\}\{\\(?:meas|srcd)\{(.+?)\}\}(?=\s|%|\\newcommand|$)",
        text,
        flags=re.M,
    )
    return dict(found)


def number(values: dict[str, str], name: str) -> float:
    raw = values[name].replace("{,}", "").replace("\\%", "").replace("+", "").strip()
    return float(raw)


def percent_interval(values: dict[str, str], name: str) -> tuple[float, float]:
    low, high = re.findall(r"[\d.]+", values[name])
    return float(low), float(high)


HEADER = "% Generated by figures/make_figures.py from numbers.tex; do not edit.\n"


def frontier(v: dict[str, str]) -> str:
    rows = [
        (letter, number(v, f"nFrCost{letter}"), number(v, f"nFrAuc{letter}")) for letter in "ABCDE"
    ]
    coords = "\n".join(f"      ({cost}, {auc}) [{letter}]" for letter, cost, auc in rows)
    return (
        HEADER
        + r"""\begin{tikzpicture}
  \begin{axis}[
      width=0.8\linewidth, height=6cm,
      xlabel={Median explanation cost per request (ms)},
      ylabel={AUC}, ymin=0.95, ymax=1.0, xmin=0,
      grid=major, grid style={gray!25},
      nodes near coords, point meta=explicit symbolic,
      every node near coord/.append style={font=\small, anchor=south},
    ]
    \addplot[mark=*, thick, blue!60!black] coordinates {
"""
        + coords
        + r"""
    };
  \end{axis}
\end{tikzpicture}
"""
    )


GROUPS = [
    ("Counterparty", "nGroupCounterparty"),
    ("Velocity", "nGroupVelocity"),
    ("Temporal", "nGroupTemporal"),
    ("Geographic", "nGroupGeographic"),
    ("Device and channel", "nGroupDevice"),
    ("Synthetic identity", "nGroupSynth"),
    ("Amount behaviour", "nGroupAmount"),
    ("Agent", "nGroupAgent"),
    ("Account profile", "nGroupProfile"),
    ("Corridor", "nGroupCorridor"),
]


def groups(v: dict[str, str]) -> str:
    names = ",".join(f"{{{label}}}" for label, _ in GROUPS)
    coords = " ".join(f"({number(v, macro)},{{{label}}})" for label, macro in GROUPS)
    floor = number(v, "nGateFloor")
    return (
        HEADER
        + r"""\begin{tikzpicture}
  \begin{axis}[
      width=0.8\linewidth, height=7cm,
      xbar, bar width=7pt, xmin=0.45, xmax=1.0,
      xlabel={AUC with one feature group only},
      symbolic y coords={"""
        + names
        + r"""},
      ytick=data, y dir=reverse, yticklabel style={font=\small},
      grid=major, grid style={gray!25},
    ]
    \addplot[fill=blue!40, draw=blue!60!black] coordinates {"""
        + coords
        + r"""};
    \draw[red!70!black, thick, dashed] (axis cs:"""
        + f"{floor}"
        + r""",{Counterparty}) -- (axis cs:"""
        + f"{floor}"
        + r""",{Corridor})
      node[pos=1, anchor=north, font=\small, fill=white] {best single feature};
  \end{axis}
\end{tikzpicture}
"""
    )


VARIANTS = [
    ("Base scenarios", "nBaseVarRecall", "nBaseVarCI"),
    ("Novel eSIM delayed drain", "nNovelRecall", "nNovelCI"),
    ("Adapted below threshold", "nAdaptRecall", "nAdaptCI"),
    ("Reversal scam", "nRevRecall", "nRevCI"),
]


def variants(v: dict[str, str]) -> str:
    names = ",".join(f"{{{label}}}" for label, _, _ in VARIANTS)
    rows = []
    for label, point_macro, interval_macro in VARIANTS:
        point = number(v, point_macro)
        low, high = percent_interval(v, interval_macro)
        rows.append(
            f"      ({point},{{{label}}}) -= ({point - low:.1f},0) += ({high - point:.1f},0)"
        )
    return (
        HEADER
        + r"""\begin{tikzpicture}
  \begin{axis}[
      width=0.8\linewidth, height=5.5cm,
      xmin=0, xmax=100, xlabel={Recall at the 1\% false-positive budget (\%), Wilson interval},
      symbolic y coords={"""
        + names
        + r"""},
      ytick=data, y dir=reverse, yticklabel style={font=\small}, enlarge y limits=0.2,
      grid=major, grid style={gray!25},
    ]
    \addplot+[only marks, mark=*, blue!60!black,
      error bars/.cd, x dir=both, x explicit] coordinates {
"""
        + "\n".join(rows)
        + r"""
    };
  \end{axis}
\end{tikzpicture}
"""
    )


FIGURES = {"fig-frontier.tex": frontier, "fig-groups.tex": groups, "fig-variants.tex": variants}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if a figure is out of date")
    args = parser.parse_args(argv)
    values = macros()
    stale = []
    for name, build in FIGURES.items():
        text = build(values)
        path = HERE / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
        else:
            path.write_text(text)
    if stale:
        print(f"make-figures: out of date: {', '.join(stale)}", file=sys.stderr)
        return 1
    print(f"make-figures: {len(FIGURES)} figures {'checked' if args.check else 'written'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
