// Generates the API client, types and Zod schemas from the contract (ADR 0080, H.4).
// Run with `pnpm api`; src/api/apiDrift.test.ts regenerates into a temporary directory and fails
// on any difference from the committed output.
import { createClient } from '@hey-api/openapi-ts';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const CONTRACT = join(import.meta.dirname, '../../contracts/openapi/fraudshield-api.yaml');
export const OUTPUT = join(import.meta.dirname, '../src/api/generated');

// Vendored generator output is not held to this project's strictest compiler flags: its fetch
// client fails exactOptionalPropertyTypes. The types it exports are still checked wherever the
// console uses them.
const HEADER =
  '// @ts-nocheck -- generated by scripts/generate-api.ts from the OpenAPI contract.\n';

function tsFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? tsFiles(join(dir, entry.name))
      : entry.name.endsWith('.ts')
        ? [join(dir, entry.name)]
        : [],
  );
}

export async function generateApi(output: string): Promise<void> {
  await createClient({
    input: CONTRACT,
    output: { path: output },
    plugins: ['@hey-api/client-fetch', '@hey-api/typescript', 'zod', '@hey-api/sdk'],
    logs: { level: 'silent' },
  });
  for (const file of tsFiles(output)) {
    writeFileSync(file, HEADER + readFileSync(file, 'utf8'));
  }
}

if (process.argv[1] === import.meta.filename) {
  await generateApi(OUTPUT);
  console.log(`wrote ${OUTPUT}`);
}
