import generated from './generated/packs.json' with { type: 'json' };
import type { Region } from './region';

/** Every country pack, keyed by ISO 3166-1 alpha-2. Generated by `pnpm region`. */
export const PACKS: Readonly<Record<string, Region>> = generated;

/** Minor units per currency, from every pack that uses it. */
export function minorUnitsByCurrency(packs: Readonly<Record<string, Region>>): Map<string, number> {
  const units = new Map<string, number>();
  for (const pack of Object.values(packs)) {
    const seen = units.get(pack.currency);
    if (seen !== undefined && seen !== pack.currencyMinorUnits) {
      throw new Error(
        `packs disagree on ${pack.currency}'s minor units: ${String(seen)} and ${String(pack.currencyMinorUnits)}`,
      );
    }
    units.set(pack.currency, pack.currencyMinorUnits);
  }
  return units;
}

/** The pack for a deployment's configured country; an unknown country stops the app. */
export function regionFor(country: string | undefined, packs = PACKS): Region {
  const region = country === undefined ? undefined : packs[country];
  if (region === undefined) {
    throw new Error(
      `VITE_FS_COUNTRY must name a country pack (${Object.keys(packs).join(', ')}), got ${String(country)}`,
    );
  }
  return region;
}
